-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 00:16:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema StockAGranel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema StockAGranel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StockAGranel` DEFAULT CHARACTER SET utf8 ;
USE `StockAGranel` ;

-- -----------------------------------------------------
-- Table `StockAGranel`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`proveedores` (
  `CUIT` VARCHAR(13) NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tiempoDeEntrega` INT NOT NULL,
  PRIMARY KEY (`CUIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`productosGranel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`productosGranel` (
  `idProductoGranel` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `tamano` INT NOT NULL,
  `unidadMedida` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  `cantidadMax` INT NOT NULL,
  `cantidadMin` INT NOT NULL,
  `idCategoria` INT NULL,
  PRIMARY KEY (`idProductoGranel`),
  INDEX `fk_productosGranel_categorias1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_productosGranel_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `StockAGranel`.`categorias` (`idCategoria`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`presentaciones` (
  `idProductoFracc` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `tamano` INT NOT NULL,
  `unidadMedida` VARCHAR(45) NOT NULL,
  `cantidadMax` INT NOT NULL,
  `cantidadMin` INT NOT NULL,
  `idProductoGranel` INT NULL,
  PRIMARY KEY (`idProductoFracc`),
  INDEX `fk_presentaciones_productosGranel1_idx` (`idProductoGranel` ASC) VISIBLE,
  CONSTRAINT `fk_presentaciones_productosGranel1`
    FOREIGN KEY (`idProductoGranel`)
    REFERENCES `StockAGranel`.`productosGranel` (`idProductoGranel`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`registroVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`registroVenta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fechaVenta` DATE NOT NULL,
  `cantidad` INT NULL,
  `idProductoFracc` INT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_registroVenta_presentaciones1_idx` (`idProductoFracc` ASC) VISIBLE,
  CONSTRAINT `fk_registroVenta_presentaciones1`
    FOREIGN KEY (`idProductoFracc`)
    REFERENCES `StockAGranel`.`presentaciones` (`idProductoFracc`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`prodProv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`prodProv` (
  `idProdIngreso` INT NOT NULL AUTO_INCREMENT,
  `fechaIngr` DATE NOT NULL,
  `fechaVto` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `CUIT` VARCHAR(13) NULL,
  `idProductoGranel` INT NULL,
  PRIMARY KEY (`idProdIngreso`),
  INDEX `fk_prodProv_proveedores1_idx` (`CUIT` ASC) VISIBLE,
  INDEX `fk_prodProv_productosGranel2_idx` (`idProductoGranel` ASC) VISIBLE,
  CONSTRAINT `fk_prodProv_proveedores1`
    FOREIGN KEY (`CUIT`)
    REFERENCES `StockAGranel`.`proveedores` (`CUIT`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_prodProv_productosGranel2`
    FOREIGN KEY (`idProductoGranel`)
    REFERENCES `StockAGranel`.`productosGranel` (`idProductoGranel`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StockAGranel`.`perdidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StockAGranel`.`perdidas` (
  `idPerdida` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `vencido` TINYINT NOT NULL,
  `fechaBaja` DATE NOT NULL,
  `idProductoFracc` INT NULL,
  PRIMARY KEY (`idPerdida`),
  INDEX `fk_perdidas_presentaciones1_idx` (`idProductoFracc` ASC) VISIBLE,
  CONSTRAINT `fk_perdidas_presentaciones1`
    FOREIGN KEY (`idProductoFracc`)
    REFERENCES `StockAGranel`.`presentaciones` (`idProductoFracc`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
